config/routes.rb
Rails.application.routes.draw do
  resources :mesagges
  root "mesagges#index"

end

app/models/mesagge.rb
class Mesagge < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/mesagges_controller.rb
class MesaggesController < ApplicationController
  before_action :set_mesagge, only: [:show, :edit, :update, :destroy]

  # GET /mesagges
  # GET /mesagges.json
  def index
    @mesagges = Mesagge.all
  end

  # GET /mesagges/1
  # GET /mesagges/1.json
  def show
  end

  # GET /mesagges/new
  def new
    @mesagge = Mesagge.new
  end

  # GET /mesagges/1/edit
  def edit
  end

  # POST /mesagges
  # POST /mesagges.json
  def create
    @mesagge = Mesagge.new(mesagge_params)

    respond_to do |format|
      if @mesagge.save
        format.html { redirect_to @mesagge, notice: 'Mesagge was successfully created.' }
        format.json { render :show, status: :created, location: @mesagge }
      else
        format.html { render :new }
        format.json { render json: @mesagge.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mesagges/1
  # PATCH/PUT /mesagges/1.json
  def update
    respond_to do |format|
      if @mesagge.update(mesagge_params)
        format.html { redirect_to @mesagge, notice: 'Mesagge was successfully updated.' }
        format.json { render :show, status: :ok, location: @mesagge }
      else
        format.html { render :edit }
        format.json { render json: @mesagge.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mesagges/1
  # DELETE /mesagges/1.json
  def destroy
    @mesagge.destroy
    respond_to do |format|
      format.html { redirect_to mesagges_url, notice: 'Mesagge was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mesagge
      @mesagge = Mesagge.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def mesagge_params
      params.require(:mesagge).permit(:message)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/mesagges_helper.rb
module MesaggesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Practica</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/mesagges/_form.html.erb
<%= form_for(@mesagge) do |f| %>
  <% if @mesagge.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@mesagge.errors.count, "error") %> prohibited this mesagge from being saved:</h2>

      <ul>
      <% @mesagge.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :message %><br>
    <%= f.text_field :message %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/mesagges/edit.html.erb
<h1>Editing Mesagge</h1>

<%= render 'form' %>

<%= link_to 'Show', @mesagge %> |
<%= link_to 'Back', mesagges_path %>

app/views/mesagges/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Lista de mensajes</h1>

<table>
  <thead>
    <tr>
      <th>Message</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @mesagges.each do |mesagge| %>
      <tr>
        <td><%= mesagge.message %></td>
        <td><%= link_to 'Show', mesagge %></td>
        <td><%= link_to 'Edit', edit_mesagge_path(mesagge) %></td>
        <td><%= link_to 'Destroy', mesagge, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Mesagge', new_mesagge_path %>

app/views/mesagges/new.html.erb
<h1>New Mesagge</h1>

<%= render 'form' %>

<%= link_to 'Back', mesagges_path %>

app/views/mesagges/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Message:</strong>
  <%= @mesagge.message %>
</p>

<%= link_to 'Edit', edit_mesagge_path(@mesagge) %> |
<%= link_to 'Back', mesagges_path %>